variables:
  AWS_DEFAULT_REGION: eu-west-1

stages:
  - deploy

cache:
  paths:
    - node_modules/

deploy_dev:
  image: "python:latest"
  stage: deploy
  before_script: 
    - pip install awscli 
    #- mkdir -p ~/.ssh     
    #- echo -e "$PRIVATE_KEY" > ~/.ssh/id_rsa     
    #- chmod 600 ~/.ssh/id_rsa     
    #- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - touch .gitlab-ci.env
    - echo "export AWS_ACCESS_KEY_ID=\"${DEV_AWS_ACCESS_KEY_ID}\"" >> .gitlab-ci.env
    - echo "export AWS_SECRET_ACCESS_KEY=\"${DEV_AWS_SECRET_ACCESS_KEY}\"" >> .gitlab-ci.env
    - echo "export AWS_DEFAULT_REGION=\"${AWS_DEFAULT_REGION}\"" >> .gitlab-ci.env
    - echo "export BUCKET_NAME=\"${DEV_BUCKET_NAME}\"" >> .gitlab-ci.env
    # - echo "export DEPLOY_SERVERS=\"${DEV_DEPLOY_SERVERS}\"" >> .gitlab-ci.env
    # - echo -e "$PRIVATE_KEY" > key.pem
    - echo -e "$DEV_CREDS" > .env
    
    
    # - cat .gitlab-ci.env
    - source .gitlab-ci.env  
    - aws s3 rm s3://$BUCKET_NAME --recursive
    - aws s3 cp . s3://$BUCKET_NAME --recursive
    # - ssh -i key.pem ubuntu@52.214.243.70 "cd  /opt/"

  environment:
    name: development
  only:
  - develop

